// Generates real eciesjs@0.4.18 + viem@2.47.6 test vectors so the Go core can
// prove cross-client wire compatibility with the s0nderlabs attn plugin.
//
// Emits testdata/vectors.json with:
//   - identity:  fixed privkey -> address + uncompressed pubkey (viem)
//   - signature: EIP-191 personal_sign over a fixed message (deterministic)
//   - ecies:     plaintext encrypted to the pubkey via eciesjs (JS -> Go decrypt)
//
// Run: bun gen-vectors.ts
import { privateKeyToAccount } from "viem/accounts";
import { encrypt } from "eciesjs";
import { writeFileSync } from "node:fs";

// Fixed, throwaway test key (NOT a real identity).
const privateKey =
  "0x4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318" as const;

const account = privateKeyToAccount(privateKey);
const address = account.address.toLowerCase();
const publicKey = account.publicKey; // 0x04... uncompressed (65 bytes)

const message = "attn-interop-challenge:550e8400-e29b-41d4-a716-446655440000-lq3x7";
const signature = await account.signMessage({ message });

const plaintext = "interop ✅ eciesjs→go: hello attn-agnostic core";
const pubHex = publicKey.slice(2); // eciesjs strips 0x in the plugin
const ct = encrypt(pubHex, new TextEncoder().encode(plaintext));
const eciesCiphertextB64 = Buffer.from(ct).toString("base64");

const vectors = {
  _note:
    "Generated by testdata/interop/gen-vectors.ts using eciesjs@0.4.18 + viem@2.47.6 (the exact versions the s0nderlabs attn plugin uses).",
  privateKey,
  address,
  publicKey,
  message,
  signature,
  plaintext,
  eciesCiphertextB64,
};

const out = new URL("../vectors.json", import.meta.url);
writeFileSync(out, JSON.stringify(vectors, null, 2) + "\n");
console.log("wrote", out.pathname);
console.log(JSON.stringify(vectors, null, 2));
